services:
  gpu-container:
    container_name: portfolio3-gpu-container
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    stdin_open: true
    tty: true
    ports:
      - "8890:8888"  # JupyterLab (GPU対応)
    volumes:
      - ./work:/home/jovyan/work  # ローカル作業用ディレクトリ
    networks:
      - portfolio-network

  postgres:
    image: postgres:17-bullseye
    container_name: portfolio3-postgres
    environment:
      POSTGRES_USER: optuna_user
      POSTGRES_PASSWORD: optuna_password
      POSTGRES_DB: optuna_db
    ports:
      - "5400:5432" # PostgreSQLのポート
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - portfolio-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio3-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: omuomu8ikd@gmail.com  # pgAdmin のログイン用メールアドレス
      PGADMIN_DEFAULT_PASSWORD: admin          # pgAdmin のログイン用パスワード
    ports:
      - "8080:80"  # 外部ポート 8080 -> 内部ポート 80
    depends_on:
      - postgres
    restart: always
    networks:
      - portfolio-network

  optuna_dashboard:
    image: ghcr.io/optuna/optuna-dashboard
    container_name: portfolio3-optuna_dashboard
    ports:
      - "8081:8080"  # 外部ポート8081を内部ポート8080にマッピング
    command: >
      postgresql+psycopg2://optuna_user:optuna_password@portfolio3-postgres:5432/optuna_db
    depends_on:
      - postgres
    restart: always
    networks:
      - portfolio-network

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge